### PR TITLE
Schema

### PR DESCRIPTION
**Pull request by yyihuang**
update schema with fk contraints and modify data insert config.

### CODE REVIEW

**Comment by dongmingli-Ben** [comment]
What has been changed in the `player_season_info.csv`?

**Comment by dongmingli-Ben** [comment]
@ANNAmiuz @ZeroAda It seems that two versions of data exist now. Which one is correct?

**Comment by dongmingli-Ben** [comment]
After checking with @ANNAmiuz, I close this PR and override the data in the master branch with the PR.

**Comment by ZeroAda** [comment]
> @ANNAmiuz @ZeroAda It seems that two versions of data exist now. Which one is correct?

I directly add the latest player_season_info.csv to master branch, so I think that's the correct one.

**Comment by dongmingli-Ben** [comment]
Two versions of data should be the same. Merged.

**Pull request merged**
